id: A6403FF8A
base_file: fE6B9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:12:55.710897
  last_modified_at: 2022-06-15 20:12:55.710901
